name: Aggiorna Dati Apex

on:
  schedule:
    - cron: '0 23 * * 1-5' # Tutti i giorni lavorativi alle 23:00
  workflow_dispatch: # Permette avvio manuale

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pandas numpy lxml html5lib streamlit
      - name: Run Backend Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python backend.py
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add apex_data.json equity.json
          git commit -m "Aggiornamento dati e Equity Curve" || echo "Nessuna modifica da pushare"
          git push
